[project]
name = "qec"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.7",
    "multiprocess>=0.70.18",
    "pymatching>=2.3.1",
    "stim>=1.15.0",
]
